### ISSUE TITLE
很棒，提个小建议，编辑时候最好可以实时预览就好了

### ISSUE THREAD

**Issue by mlboy** [aisuda/amis-editor-demo#10]
很棒，提个小建议，编辑时候最好可以实时预览就好了，右边一直是选择模式，很容易点击，丢失掉当前编辑的焦点

**Comment by 2betop** [comment]
但是怎么切到你想编辑的组件？

**Comment by anye931123** [comment]
项目地址：https://github.com/brick-design/react-visual-editor，应该满足你的要求了

**Comment by wibetter** [comment]
欢迎使用新版amis-editor，当前已支持实时预览，可在这里体验：https://aisuda.github.io/amis-editor-demo/#/edit/0。
