### ISSUE TITLE
执行npm run gh-pages生成的index.html中引有两个js文件没有打包生成

### ISSUE THREAD

**Issue by lhkg1988** [aisuda/amis-editor-demo#100]
执行npm run gh-pages生成的index.html中引有两个js文件没有打包生成，amis-editor-demo/n/copy-to-clipboard/index_32ff0e5.js ，导致报错
<img width="955" alt="bug" src="https://user-images.githubusercontent.com/7578173/125759348-8af981dc-ccda-45b6-9d15-47efc5c40a1a.png">

**Comment by lengqingfeng** [comment]
同问

**Comment by lhkg1988** [comment]
还有希望吗？感觉提了那么多的issue都没有关闭，还能等到回复吗？

**Comment by lhkg1988** [comment]
找到问题了，安装的依赖包不对，只能用npm install来安装，用cnpm或者yarn安装build出来的都有问题
