### ISSUE TITLE
点击新增页面，填写后报错及全部导出按钮不可用

### ISSUE THREAD

**Issue by impossiblepet** [aisuda/amis-editor-demo#101]
出现两个错误：
1、点击新增页面，填写后报错，Cannot read property 'props' of null，官方DEMO中也是一样的问题

2、全部导出按钮不可用

**Comment by lhtuling** [comment]
问题+1  持续差不多1个多月了!

**Comment by lhtuling** [comment]
最主要的这个
1、点击新增页面，填写后报错，Cannot read property 'props' of null，官方DEMO中也是一样的问题

**Comment by 123geshuai** [comment]
先这样改一下，暂时用着
具体原因，不知道。
非官方答案：
方法1
1、编译出来有个npm.js文件，全局搜索control:valdiate，下一行有finalValidate函数
把这个finalValidate_1(this.props.data, _this.getValue(), name)里的this，换成_this。

![image](https://user-images.githubusercontent.com/8012462/128675247-62155cd8-0b2b-4125-8b2a-365d9607da4b.png)
方法2(没验证)
这个npm.js是编译出来的，找到wrapControl.tsx文件，修改一下，重新生成npm.js。

**Comment by 123geshuai** [comment]
接上
方法2:
到node_modules的amis里找到lib/renderers/Form/wrapControl.js文件，把函数this.hook2的定义方法修改一下,是this的指向出错导致的。修改之后，重新npm run start和npm run dev。

![image](https://user-images.githubusercontent.com/8012462/128676840-e9489946-5952-4df4-af58-b5bab6097e68.png)
在amis-master的源码中，hook3和hoo2的定义方式不一样的。可以给他们提issues。
![image](https://user-images.githubusercontent.com/8012462/128677089-68dad824-8879-4ff2-96dc-036de44a2a53.png)

**Comment by impossiblepet** [comment]
> 先这样改一下，暂时用着
> 具体原因，不知道。
> 非官方答案：
> 方法1
> 1、编译出来有个npm.js文件，全局搜索control:valdiate，下一行有finalValidate函数
> 把这个finalValidate_1(this.props.data, _this.getValue(), name)里的this，换成_this。注意有两处
> 
> ![image](https://user-images.githubusercontent.com/8012462/128675540-068fe528-4087-459d-924e-7b94b1406676.png)
> 
> 方法2(没验证)
> 这个npm.js是编译出来的，找到wrapControl.tsx文件，修改一下，重新生成npm.js。

方法1 ，测试有效，全部导出的按钮不可用的那个可以改哪个

**Comment by lhtuling** [comment]
好像修复了!大家试试看!

**Comment by wibetter** [comment]
1、新增页面功能，目前能正常使用；
2、全部导出功能只是一个静态展示按钮，目前还未支持导出功能。
请使用新版Editor，目前已升级至4.1.0-beta.24。
