### ISSUE TITLE
配置弹窗内容 无法保存Json

### ISSUE THREAD

**Issue by cube3power** [aisuda/amis-editor-demo#102]
版本:  
"amis": "^1.2.2-beta.12",
"amis-editor": "^3.0.7-beta.3",

操作:
![image](https://user-images.githubusercontent.com/5474892/127796244-09d92045-bdbf-42d0-87a6-ae5ea0b18a08.png)

点击 配置弹窗内容
![image](https://user-images.githubusercontent.com/5474892/127796302-c96cbbff-6b49-402f-81ed-100dd907f2e5.png)

保存之后
![image](https://user-images.githubusercontent.com/5474892/127796344-446dc336-b2e3-4ee2-ad8e-70535ad1d6a9.png)

**Comment by elinoxp** [comment]
我也遇到同样问题，换了好几个版本都是类似问题
