### ISSUE TITLE
左侧控件是否可以隐藏不常用的控件

### ISSUE THREAD

**Issue by daifuyang** [aisuda/amis-editor-demo#103]
你好，请问左侧编辑器可以自定义显示区块吗？控件太多了，希望可以暴露出配置我们自主定义配置

**Comment by fxwing** [comment]
同问

**Comment by webplus** [comment]
同问

**Comment by wibetter** [comment]
可以通过这种方式隐藏Editor预置组件：
![image](https://user-images.githubusercontent.com/11958920/169705286-aed0ac8e-2b1b-4877-8b18-c380acec2bbf.png)
