### ISSUE TITLE
Amis-editor documentation

### ISSUE THREAD

**Issue by phxgbl** [aisuda/amis-editor-demo#104]
Hello friends, 

    I would like to know more about amis-editor. I know that it's not open source. But is it possible to get editor documentation?

**Comment by wibetter** [comment]
目前只有一份旧版的文档：https://baidu.gitee.io/aisuda-docs/%E9%A1%B5%E9%9D%A2%E8%AE%BE%E8%AE%A1/%E6%99%AE%E9%80%9A%E9%A1%B5%E9%9D%A2%E8%AE%BE%E8%AE%A1/%E6%99%AE%E9%80%9A%E9%A1%B5%E9%9D%A2%E8%AF%B4%E6%98%8E。
新版的说明文档还在编写中。
