### ISSUE TITLE
编辑器list组件与hbox组件结合使用报错，官方示例在可视化编译器中不可用

### ISSUE THREAD

**Issue by relaxing0314** [aisuda/amis-editor-demo#105]
react_devtools_backend.js:2557 The above error occurred in the <HBoxRenderer> component:
    in HBoxRenderer (created by Renderer)
    in Renderer (created by ListItemRenderer)
    in div (created by ListItemRenderer)
    in div (created by ListItemRenderer)
    in ListItemRenderer (created by Renderer)
    in Renderer (created by ListRenderer)
    in div (created by ListRenderer)
    in div (created by ListRenderer)
    in ListRenderer (created by WithStore(ListRenderer))
    in WithStore(ListRenderer) (created by t)
    in t (created by WithStore(ListRenderer))
    in WithStore(ListRenderer) (created by Renderer)
    in Renderer (created by PanelRenderer)
    in t (created by PanelRenderer)
    in div (created by PanelRenderer)
    in div (created by PanelRenderer)
    in PanelRenderer (created by t)
    in t (created by t)

**Comment by wibetter** [comment]
Hbox组件目前已下线，布局更建议使用分栏组件。
