### ISSUE TITLE
npm i 之后public文件为空

### ISSUE THREAD

**Issue by break60** [aisuda/amis-editor-demo#108]
hi，我clone了master分支代码，运行的时候public文件始终为空
![image](https://user-images.githubusercontent.com/28628088/131943062-141c85c6-467f-42a1-bbf0-08750ce6e741.png)
![image](https://user-images.githubusercontent.com/28628088/131943094-792f7dd7-ace7-4b32-ac37-a8b3c0b2630f.png)

**Comment by nwind** [comment]
要 `npm run dev`
