### ISSUE TITLE
自定义组件示例

### ISSUE THREAD

**Issue by thbgh** [aisuda/amis-editor-demo#113]
希望能提供自定义组件完善一点的示例

**Comment by thbgh** [comment]
@nwind @2betop @taosher @fayeah 
README.md中 扩充自定义编辑器（新版）例子有更多配置说明吗?

**Comment by wibetter** [comment]
目前amis-editor已将内置的plugin源码开放出来了，方便各位参照定制自己自定义组件，组件plugin这部分的源码可以在这里查看：amis-editor-demo/node_modules/amis-editor/src/plugin。
