### ISSUE TITLE
Unhandled Rejection (Error): Cannot find module 'axios'

### ISSUE THREAD

**Issue by crizydevl** [aisuda/amis-editor-demo#117]
`
return (
        <div>
            <Editor value={jsonCFG} onChange={(e) => {console.log('e', e)}} />
            
        </div>
    )
`
直接引用为啥会报这个错误？

**Comment by wibetter** [comment]
请贴完整的代码，

**Comment by wibetter** [comment]
单独使用amis-editor时，可以手动补充一下axios依赖，也可以选择升级amis-editor到最新版本：5.2.1-beta.32。
