### ISSUE TITLE
试用新版「页面设计器」

### ISSUE THREAD

**Issue by wibetter** [aisuda/amis-editor-demo#118]
[新版「页面设计器」](https://aisuda.github.io/amis-widget/test/preview.html)

**Comment by Twelveeee** [comment]
比上一版更清爽更流畅，nice

**Comment by agileago** [comment]
@wibetter webcomponent组件无法增加属性

**Comment by taolei1990** [comment]
dev 模式图标正常 build打包后图标就不显示了 这个要怎么办
![image](https://user-images.githubusercontent.com/23173640/158339366-e4d2fa6b-eb25-4069-9389-1a6149a148cc.png)

**Comment by wibetter** [comment]
@taolei1990 应该是构建的问题，但不影响试用哈，等抽空修复一下，

**Comment by taolei1990** [comment]
@wibetter  图标问题解决了是因为webfonts里面图标文件为空了 把文件补齐就可以了 我看你们介绍是不开源但是可以使用包括商用的嘛 这个能用在公司项目上会不会侵权啊

**Comment by wibetter** [comment]
@taolei1990 
![image](https://user-images.githubusercontent.com/11958920/169690351-c61abaab-24b4-46d5-b356-23d721507e8b.png)
