### ISSUE TITLE
请问@fex/amis-editor 有开源计划吗？

### ISSUE THREAD

**Issue by dxfstart521** [aisuda/amis-editor-demo#12]
请问@fex/amis-editor 有开源计划吗？

**Comment by 2betop** [comment]
改名叫 amis-editor 外部也能使用了

**Comment by dxfstart521** [comment]
hello,滴滴这边中台系统正在大力推广使用amis，内部已经有项目在使用，后面会大力推广。想邀请大佬来滴滴做个关于amis和amis可视化的分享，请问大佬有兴趣吗？期待大佬的回复。希望可以达成合作。


祝好!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fex-team/amis-editor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 上午9:44
收件人:&nbsp;"fex-team/amis-editor"<amis-editor@noreply.github.com&gt;;
抄送:&nbsp;"395576971"<395576971@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fex-team/amis-editor] 请问@fex/amis-editor 有开源计划吗？ (#12)





 
改名叫 amis-editor 外部也能使用了

**Comment by dxfstart521** [comment]
hello, 目前滴滴这边中台系统正在大力推广使用amis，内部已经有项目在使用，后面会大力推广。想邀请大佬来滴滴做个关于amis和amis可视化的分享，请问大佬有兴趣吗？期待大佬的回复。希望可以达成合作。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fex-team/amis-editor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 上午9:44
收件人:&nbsp;"fex-team/amis-editor"<amis-editor@noreply.github.com&gt;;
抄送:&nbsp;"395576971"<395576971@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fex-team/amis-editor] 请问@fex/amis-editor 有开源计划吗？ (#12)





 
改名叫 amis-editor 外部也能使用了

**Comment by FatDong1** [comment]
哈哈哈，现在不用从node_modules里面抠出来用了

**Comment by MyCupOfTeaOo** [comment]
会开放源码吗

**Comment by MyCupOfTeaOo** [comment]
我现在跟项目的mobx冲突,又不能降级,必须要改源码....

**Comment by vjiuzhou** [comment]
> 会开放源码吗

其实不用开源也可以支持绝大部分使用场景了， 参考这个成熟的集成amis产品https://gitee.com/uniappadmin/uniappadmin

**Comment by wibetter** [comment]
目前amis-editor已将内置的plugin源码开放出来了，方便各位参照定制自己的自定义组件，这部分的源码可以在这里查看：amis-editor-demo/node_modules/amis-editor/src/plugin。
