### ISSUE TITLE
amis-editor-demo预览模式下header的配置无效. 

### ISSUE THREAD

**Issue by MrTao1** [aisuda/amis-editor-demo#127]
https://github.com/baidu/amis/issues/3240#issue-1085512266

**Comment by wangyalong** [comment]
请问这个有人关注吗，我的3.36.11 版本也不生效

**Comment by wibetter** [comment]
已经修复了，相关改动点：https://github.com/aisuda/amis-editor-demo/commit/1823d4cbf42e414e07ec48dccf99547b06539353。
