### ISSUE TITLE
扩充自定义编辑器（新版）显示找不到对应的渲染器

### ISSUE THREAD

**Issue by heisen16129** [aisuda/amis-editor-demo#128]
![image](https://user-images.githubusercontent.com/57136111/157160851-e6d29f9b-6bbc-4408-8c2d-3edd1128946f.png)

**Comment by wibetter** [comment]
确认一下是否将自定义amis渲染器import进来，
![image](https://user-images.githubusercontent.com/11958920/169705384-81cbe25d-b890-40ba-b430-88107debf74d.png)

**Comment by wibetter** [comment]
请将amis和amis-editor相关模块升级到最新版本，再验证下是否还有这个问题。
