### ISSUE TITLE
demo内置自定义组件在移动端模式下报错

### ISSUE THREAD

**Issue by toyshome** [aisuda/amis-editor-demo#129]
组件菜单【其他】-> 【自定义组件】。拖到页面中，打开移动端开关，自定义组件渲染报错[类型错误，无法渲染]

**Comment by wibetter** [comment]
已经修复，相关代码改动请看：https://github.com/aisuda/amis-editor-demo/commit/4e9544d6e390c7ee42c12b7e717a72e426ff2d21。
