### ISSUE TITLE
自定义一个组件后，不可以把其他组件通过拖拉拽的方式放到自定义组件中吗

### ISSUE THREAD

**Issue by Ding4514** [aisuda/amis-editor-demo#133]

**Comment by wibetter** [comment]
需要改成自定义容器类型组件才支持内部插入其他组件，你可以参考 node_modules/amis-editor/plugin/Container 写一个自定义容器组件：
![image](https://user-images.githubusercontent.com/11958920/169680611-5da42c6f-c704-4a25-85c8-d8eb35df37f1.png)
