### ISSUE TITLE
老版本无法正常运行

### ISSUE THREAD

**Issue by lijianmincn** [aisuda/amis-editor-demo#134]
上个版本之前可以运行，最近运行报错，请问该如何解决？
版本：
"amis": "^1.0.18-beta.9",
"amis-editor": "2.0.6",
运行之后浏览器报错：
Uncaught SyntaxError: Cannot use import statement outside a module
ncaught [ModJS] Cannot find module `node_modules/tslib/tslib`

![image](https://user-images.githubusercontent.com/26019815/161771402-528d10c7-566d-43af-b402-2822b7d5658f.png)

**Comment by wibetter** [comment]
请使用新版Editor，目前已升级到 4.1.0-beta.24。
