### ISSUE TITLE
比官网demo显示的组件少一些？

### ISSUE THREAD

**Issue by jeffcao** [aisuda/amis-editor-demo#135]
http://aisuda.github.io/amis-editor-demo
以上是官网的demo链接，因为访问github比较慢，想在本地跑一个编辑器，但是拿这个源码编译出来的编辑器中组件比官网的少一些 ? 是我代码没拿到最新吗 ？

**Comment by pengxiang-git** [comment]
对啊，咋回事

**Comment by wibetter** [comment]
@jeffcao 你说的官网demo是指哪个，方便截图看下哈

**Comment by wibetter** [comment]
目前你说的少一部分组件，有两部分原因，1是Editor本身下线了部分重复的组件，2是在爱速搭官网中，会对应新增一些平台相关组件，比如: 模型表单、模型列表等。
