### ISSUE TITLE
chart组件无法显示图表问题

### ISSUE THREAD

**Issue by Maoqiu-ps** [aisuda/amis-editor-demo#138]
页面没有报错，不用后端api接口数据，前端直接给的数据都无法显示图表

**Comment by Maoqiu-ps** [comment]
` (function () {
        let amis = amisRequire('amis/embed');
        let amisJSON = {
          "type": "page",
          "debug": true,
          "body": [
            {
              "type": "chart",
              "name": "platform_pie_chart",
              "height": "auto",
              "config": {
                "tooltip":{
                    "trigger":"item"
                },
                "title":{
                    "text":"渠道来源占比"
                },
                'legend': {
                    'top': 'top'
                  },
                'toolbox': {
                    'show': true,
                    'feature': {
                      'mark': {
                        'show': true
                      },
                      'dataView': {
                        'show': true,
                        'readOnly': false
                      },
                      'restore': {
                        'show': true
                      },
                      'saveAsImage': {
                       'show': true
                      }
                    }
                },
                'series': [
                    {
                      'type': 'pie',
                      'roseType': 'area',
                      'itemStyle': {
                        'borderRadius': 3
                      },
                      'data': [{name: "IOS", value: 100}, {name: "WIN", value: 100}],
                      "label":{
                        "formatter":"{d}%"
                      }
                    }
                ]
              }
            },
          ]
        };
        let amisScoped = amis.embed('#root', amisJSON);
	  })();`

**Comment by Maoqiu-ps** [comment]
```
 (function () {
        let amis = amisRequire('amis/embed');
        let amisJSON = {
          "type": "page",
          "debug": true,
          "body": [
            {
              "type": "chart",
              "name": "platform_pie_chart",
              "height": "auto",
              "api": "api/order/data_vis?type=platform_pie",
              "config": {
                "tooltip":{
                    "trigger":"item"
                },
                "title":{
                    "text":"渠道来源占比"
                },
                'legend': {
                    'top': 'top'
                  },
                'toolbox': {
                    'show': true,
                    'feature': {
                      'mark': {
                        'show': true
                      },
                      'dataView': {
                        'show': true,
                        'readOnly': false
                      },
                      'restore': {
                        'show': true
                      },
                      'saveAsImage': {
                       'show': true
                      }
                    }
                },
                'series': [
                    {
                      'type': 'pie',
                      'roseType': 'area',
                      'itemStyle': {
                        'borderRadius': 3
                      },
                      'data': [{name: "IOS", value: 100}, {name: "WIN", value: 100}],
                      "label":{
                        "formatter":"{d}%"
                      }
                    }
                ]
              }
            },
          ]
        };
        let amisScoped = amis.embed('#root', amisJSON);
	  })();
```

**Comment by wibetter** [comment]
图表schema没问题，我这边copy出来能正常渲染，怀疑是其他地方影响了。
