### ISSUE TITLE
扩充自定义编辑器（新版）显示类型错误无法渲染

### ISSUE THREAD

**Issue by amor123456** [aisuda/amis-editor-demo#139]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/43602885/170951410-fd8d642c-d25f-4f01-be32-caa1d0b3d8ed.png">

**Comment by wibetter** [comment]
贴一下这个自定义组件的plugin代码，

**Comment by amor123456** [comment]
import { BasePlugin } from "amis-editor";

export class MyRendererPlugin extends BasePlugin {
  rendererName = "my-renderer";

  // 暂时只支持这个，配置后会开启代码编辑器
  $schema = "/schemas/UnkownSchema.json";

  // 用来配置名称和描述
  name = "自定义渲染器";

  description = "这只是个示例";

  // tag，决定会在哪个 tab 下面显示的
  tags = ["自定义", "表单项"];

  // 图标
  icon = "fa fa-user";

  // 用来生成预览图的
  previewSchema = {
    type: "my-renderer",
    target: "demo"
  };

  // 拖入组件里面时的初始数据
  scaffold = {
    type: "my-renderer",
    target: "233"
  };

  // 右侧面板相关
  panelTitle = "自定义组件";

  panelControls = [
    {
      type: "tabs",
      tabsMode: "line",
      className: "m-t-n-xs",
      contentClassName: "no-border p-l-none p-r-none",
      tabs: [
        {
          title: "常规",
          controls: [
            {
              name: "target",
              label: "Target",
              type: "text"
            }
          ]
        },

        {
          title: "外观",
          controls: []
        }
      ]
    }
  ];
}

**Comment by wibetter** [comment]
plugin 看着没啥问题，检查下是不是没有执行注册：
![image](https://user-images.githubusercontent.com/11958920/171150875-d9ae4144-79c3-4d02-9b2d-cda04022453e.png)

**Comment by amor123456** [comment]
我是把amis-editor作为插件引入项目的，请问应该在哪里注册啊？

**Comment by wibetter** [comment]
在项目中import 一下这个 MyRenderer.tsx 文件即可。
