### ISSUE TITLE
中间画布区域能够实现自由拖拽调整位置和大小吗

### ISSUE THREAD

**Issue by VonnOoO** [aisuda/amis-editor-demo#141]
现在这个版本很好了，就是如果中间画布区域能够实现自由拖拽调整位置和大小就完美了。

期望：组件被拖入后可以自由拖拉组件的位置和大小

vue中见过这样插件，这样能够更加贴合低代码，减少数据手动输入。

thankyou

**Comment by wibetter** [comment]
后续会增加自由布局容器，里面插入的元素可以自由拖拽位置，另外自由容器也会提供拖拽宽度的能力，不过这些还在计划中，还没排上，可能需要等一段时间才能用上。
备注：不建议过多使用这类自由容器，因为自由容器中的元素都是绝对布局的，不方便后续进行代码级的维护。

**Comment by wibetter** [comment]
amis-editor 升级到5.2.1-beta.31后，新增的布局容器，改为 固定 或者 绝对 定位，即可支持自由拖拽调整位置。
