### ISSUE TITLE
amis-editor 这个库可以开源吗？

### ISSUE THREAD

**Issue by JimFirst** [aisuda/amis-editor-demo#143]
如题：amis-editor 这个库可以开源吗？半开源状态有点难受

**Comment by anli001024** [comment]
+1

**Comment by SteveCGC** [comment]
lowcode engine 都开源了，建议这个也开源吧，一起为开源社区做点贡献吧

**Comment by Jarod-Xie** [comment]
+1

**Comment by zhangyang215** [comment]
+1

**Comment by nwind** [comment]
npm 安装后有个 src 目录，包含所有官方插件

**Comment by hyzx86** [comment]
> npm 安装后有个 src 目录，包含所有官方插件

看到了，但是里面的代码引用了部分未导出的类

比如 SelectControlPlugin ，这个对象 可以代码中直接导入，但是运行会报 路径下这个东西不存在
Can't resolve 'amis-editor/dist/plugin/Form/Select'
我开始的计划是 通过继承 来修改  它的 panelBodyCreator  为其增加自定义面板  
```
export class EOCSelectControlPlugin extends SelectControlPlugin {
```

```
  panelBodyCreator = (context: any) => {
    var selectPlugin = super.panelBodyCreator(context);
    console.log('11111111111111111111111111111111selectPlugin', selectPlugin);
    return merge(selectPlugin, {
      tabs: [
        {
          title: 'EOC设定',
          body: [
            {
              type: 'select',
              label: '关联类型',
              options: [
                { label: '菜单管理', value: 'AntdMenuItem' },
                { label: 'Amis页面', value: 'AmisSchema' },
              ],
            },
          ],
        },
      ],
    });
  };
```
码都撸好了，但是报各种找不到文件  Module not found: Error: Can't resolve 'amis-editor/dist/plugin/Form/Select' in 'xxxx\AMISComponent\components'


如果我把代码SelectControlPlugin 的代码拷贝出来，需要调用这个东西 ：`getEventControlConfig`
引入正常，运行 又不存在。。 
😢

**Comment by wibetter** [comment]
已开源：https://github.com/aisuda/amis-editor-demo/issues/194

**Comment by hyzx86** [comment]
真·喜大普奔
