### ISSUE TITLE
amis-editor 无法添加headers 不生效，请问这个怎么解决

### ISSUE THREAD

**Issue by wangyalong** [aisuda/amis-editor-demo#145]
scheme：
![image](https://user-images.githubusercontent.com/23610620/175459666-4e904855-34c7-4605-977a-1ad6965efc90.png)
请求：
![image](https://user-images.githubusercontent.com/23610620/175459738-c53c02c4-1471-430f-98f7-cfe015a7861c.png)

**Comment by wibetter** [comment]
刚验证了一下，添加的header在请求中能看到：
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/11958920/226893958-ef9b44ef-03ba-4cbb-abaa-b4b027ad6969.png">
