### ISSUE TITLE
amis-editor-demo 丢失页面设计数据

### ISSUE THREAD

**Issue by ghost** [aisuda/amis-editor-demo#149]
1、打开https://aisuda.github.io/amis-editor-demo
2、新增页面aaa
![iShot_2022-07-26_17 17 30](https://user-images.githubusercontent.com/26927826/180971618-c1a62d00-7ca2-434b-8631-b136cd668feb.png)
3、编辑页面aaa，放置页面组件
![iShot_2022-07-26_17 17 55](https://user-images.githubusercontent.com/26927826/180971636-42d54664-0bb2-459d-b4f9-e9b33e5e0eed.png)
4、退出aaa页面设计，回到页面列表
5、新增页面bbb
![iShot_2022-07-26_17 18 11](https://user-images.githubusercontent.com/26927826/180971645-76d8e6fe-96ae-4b1c-b3d7-2dd72b01c797.png)
6、编辑页面bbb，放置页面组件
![iShot_2022-07-26_17 18 25](https://user-images.githubusercontent.com/26927826/180971650-e341d804-6ead-4411-bb37-8a9f59687002.png)
7、退出bbb页面设计，回到页面列表
8、编辑页面aaa，发现aaa页面之前设计的组件丢失
![iShot_2022-07-26_17 18 39](https://user-images.githubusercontent.com/26927826/180971655-9ce883ab-0be4-431a-8302-2460d6d33345.png)

操作系统 MacOS
浏览器 Edge 103.0.1264.62
UserAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62

**Comment by wibetter** [comment]
已经修复。
