### ISSUE TITLE
curd 编辑不刷新

### ISSUE THREAD

**Issue by yuhonyon** [aisuda/amis-editor-demo#150]
mock数据下 编辑会刷新
![image](https://user-images.githubusercontent.com/9654460/181141949-61810daa-24d0-4d23-8e49-0402f26533ac.png)

接口数据下 编辑不刷新
![image](https://user-images.githubusercontent.com/9654460/181142120-6120da34-a0a2-4c5f-b63d-ea3f18fe84bb.png)

**Comment by wertycn** [comment]
+1  CURD 配置真实接口后，添加组件必须预览后才能显示

**Comment by wibetter** [comment]
欢迎使用新版amis-editor，当前已支持实时预览，可在这里体验：[https://aisuda.github.io/amis-editor-demo/#/edit/0。](https://aisuda.github.io/amis-editor-demo/#/edit/0%E3%80%82)

右侧配置改动后，画布区能实时预览：
<img width="1365" alt="image" src="https://github.com/aisuda/amis-editor-demo/assets/11958920/44017999-78f1-4cdb-8c7e-2da173635695">
