### ISSUE TITLE
对批量提交好像很不友好，有解决方案吗？

### ISSUE THREAD

**Issue by chxuxu** [aisuda/amis-editor-demo#153]
比如有个列表的数据源不是通过接口更新的，而是另一个有独立数据域的组件生成的，如何优雅的更新列表的数据域？

**Comment by wibetter** [comment]
CRUD组件支持批量操作，详细请见文档：https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E6%89%B9%E9%87%8F%E6%93%8D%E4%BD%9C。
