### ISSUE TITLE
bug 升级amis 2.0.2 -> 2.1.0   事件面板 报错 Error: 找不到对应的渲染器 Path: dropdown-button

### ISSUE THREAD

**Issue by yuhonyon** [aisuda/amis-editor-demo#154]
bug 升级amis 2.0.2 -> 2.1.0   事件面板 报错 Error: 找不到对应的渲染器 Path: dropdown-button

**Comment by wibetter** [comment]
请使用新版amis（2.5.0-rc.0），dropdown-button 组件并未下线，可正常使用。
