### ISSUE TITLE
保存接口

### ISSUE THREAD

**Issue by zhouqiang1983** [aisuda/amis-editor-demo#157]
因为editor经常崩溃或误操作，导致画了半天的界面消失，需要重做。
因此有个建议：
能否实现一个“保存”按钮，保存按钮，实现post方式的接口提交，至于是什么接口地址，可以由我们自定义传入，实现保存至数据库。
能行吗？

**Comment by wibetter** [comment]
现在已增加前端实时缓存功能，每一次操作都会自动存储一次。
