### ISSUE TITLE
amis-editor什么时候会拆分完成，拆分之后可以定制化编辑器吗

### ISSUE THREAD

**Issue by xinlanlan** [aisuda/amis-editor-demo#159]
amis-editor大概什么时候拆分完成呢，拆分完成后可以定制化一些编辑的插件吗，想lowcode-engine那样，不仅仅是自定义组件

**Comment by hyzx86** [comment]
拆分？

**Comment by hyzx86** [comment]
lowcode-engine 好用不？

**Comment by wibetter** [comment]
amis-editor支持通过扩充plugin的形式进行定制和改造，也可以用于添加自定义组件，相关文档请见：https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react
