### ISSUE TITLE
自定义组件如何扩展通过amis的组件生成的页面JSON？

### ISSUE THREAD

**Issue by rodchen-king** [aisuda/amis-editor-demo#16]
举例说明：我们在crud的组件上需要做一些数据配置，然后当成一个基本的控件使用，应该怎么做？

**Comment by zzq0826** [comment]
+1

**Comment by wibetter** [comment]
请看下这个使用文档：https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react
