### ISSUE TITLE
提示『remark』已经存在，大概什么原因？

### ISSUE THREAD

**Issue by hongv** [aisuda/amis-editor-demo#160]
[@umijs/runtime] load component failed Error: The renderer with name "remark" has already exists, please try another name!

**Comment by zhbHym** [comment]
I have the same problem. Have you solved it

**Comment by hyzx86** [comment]
> I have the same problem. Have you solved it

咋修的嘞？求赐教

**Comment by hyzx86** [comment]
已解决 https://github.com/baidu/amis/issues/4877

**Comment by wibetter** [comment]
**问题分析**：
出现这个问题的原因是因为amis打包了两份（lib和esm都打包进来了），导致重复注册渲染器。排查了一下，根本原因是因为此前的amis-editor-core只有一个lib，但其他模块（amis-editor、amis、amis-core）等都支持esm使用模式，所有导致amis的lib模块和esm模块都打包了一次。
**解决方式1**: 将amis-editor和amis-editor-core 都升级到5.2.1-beta.20，这个版本的amis-editor-core提供esm模块；
**解决方式2**: 如果坚持使用旧版的话，可以在webpack中处理下，在 webpack配置文件中添加 [resolve.conditionNames](https://www.webpackjs.com/configuration/resolve#resolveconditionnames): ['require']，可控制构建过程中指使用lib模块。

**Comment by hyzx86** [comment]
嗯。。升级后编译不过去了~
然后降级到 5.2.1-beta-2 也不行- - 都是报这个  amis-editor-core/lib/style.css  编译失败~
跑不起来~ 回不去了
![image](https://user-images.githubusercontent.com/15613121/204081044-d8ca2223-3e58-4064-997d-ae848ddb36e5.png)

**Comment by hyzx86** [comment]
然后降级到 5.2.0-beta-2  就可以了~

**Comment by wibetter** [comment]
@hyzx86 怀疑你装的amis-editor-core版本不对，npm list amis-editor-core看一下安装的版本是多少。5.2.1-beta.22 版本中是有这个css文件的：
<img width="610" alt="image" src="https://user-images.githubusercontent.com/11958920/204143745-fb579f32-cdf9-4a1c-92e5-f32d2c555150.png">

**Comment by hyzx86** [comment]
@wibetter 马上测试

**Comment by hyzx86** [comment]
刚才更新到最新版了
``` bash
yarn add amis-editor-core amis-editor
```
噢 我的项目每次 会提示让选择版本。。
```
Couldn't find any versions for "amis-editor-core" that matches "*"
? Please choose a version of "amis-editor-core" from this list: 5.2.1-beta.26
........
info All dependencies
├─ amis-editor-core@5.2.1-beta.26
├─ amis-editor@5.2.1-beta.26
└─ i18n-runtime@0.0.22


 npm list amis-editor-core
├── amis-editor-core@5.2.1-beta.26
└─┬ amis-editor@5.2.1-beta.26
  └── amis-editor-core@5.2.1-beta.26 deduped
```


![image](https://user-images.githubusercontent.com/15613121/204144120-9be53cd5-d3d2-41a6-a991-1c9604b66792.png)

**Comment by hyzx86** [comment]
@wibetter 
更新后跑起来还是这样子。。
![image](https://user-images.githubusercontent.com/15613121/204144250-b121eca1-85a9-4dc5-a4d3-1f56baab6162.png)

**Comment by sniper-xx** [comment]
> @wibetter 更新后跑起来还是这样子。。 ![image](https://user-images.githubusercontent.com/15613121/204144250-b121eca1-85a9-4dc5-a4d3-1f56baab6162.png)

editor样式当作静态资源引入就行。 但采用umi集成后的最终效果还是存在问题。

**Comment by sniper-xx** [comment]
> @hyzx86 看报错是你们构建工具的问题。

有关于umi配置的解决方案吗？

**Comment by hyzx86** [comment]
> > @hyzx86 看报错是你们构建工具的问题。
> 
> 有关于umi配置的解决方案吗？

没有啊。。 你这边解决掉的话 求分享下啊

**Comment by wibetter** [comment]
可以调整下你的css-loader：
    loader: 'css-loader',
    options: {
      url: {
        filter: (url, resourcePath) => {
          if (url.startsWith('data:')) {
            return false;
          }
          return true;
        }
      },
   }

**Comment by wibetter** [comment]
@hyzx86 amis-editor-core 请这个最新的版本：5.2.1-beta.31。
5.2.1-beta.30 版本中的css有部分图片丢失问题。

**Comment by hyzx86** [comment]
> 5.2.1-beta.30 版本中的css有部分图片丢失问题。

对对。。。今天还在查 不知道咋回事呢。。 以为是我打包工具的问题

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/204970152-887bbd8d-5fca-46b3-9238-216d2501ac25.png)
@wibetter 你说的图片丢失。。是指这些图标么？
现在是
```
  "amis-editor": "5.2.1-beta.31",
   "amis-editor-core": "5.2.1-beta.31",
```
![image](https://user-images.githubusercontent.com/15613121/204970313-eb1fce04-ff12-4a4b-aa18-bda93364f8eb.png)

**Comment by wibetter** [comment]
是指这些：
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/11958920/204982997-d35ac867-aab5-4790-877a-d5243a9d3d79.png">

**Comment by sniper-xx** [comment]
> 是指这些： <img alt="image" width="1303" src="https://user-images.githubusercontent.com/11958920/204982997-d35ac867-aab5-4790-877a-d5243a9d3d79.png">

 除此以为，还存在两侧区块滚动失效的问题。 既： 组件面板和属性面板滚动事件失效。

**Comment by hyzx86** [comment]
我这个。。可能是啥问题呢~
看样子是 字体没加载成功~
