### ISSUE TITLE
amis-editor 5.1.9  中的 select 为啥没有  autocomplete  的配置了啊

### ISSUE THREAD

**Issue by hyzx86** [aisuda/amis-editor-demo#161]
如题。。
![image](https://user-images.githubusercontent.com/15613121/189861867-6df9cf5e-c39e-4d33-adc4-c66e593d5de3.png)

**Comment by rujianwang** [comment]
请问之前你用的哪个版本有的？

**Comment by qianxiaofendou** [comment]
![image](https://user-images.githubusercontent.com/20673152/195020836-9a073d41-929e-4a68-97b9-7fb9eef5687a.png)

@rujianwang 这个在新版本的编辑里面是没有的，5.1.9版本之前是有的(且api配置和自动完成是可以同时存在的，在某些场景下两个配置是都需要的)，如下图：
![image](https://user-images.githubusercontent.com/20673152/195022128-6b198878-5829-41fb-8862-c1599cbe6625.png)

**Comment by wibetter** [comment]
新版Editor已下线这个autocomplete配置功能，如有需要可以在左侧代码面板，手动补充 autoComplete 相关配置数据。
