### ISSUE TITLE
请教如何修改现有插件？

### ISSUE THREAD

**Issue by hyzx86** [aisuda/amis-editor-demo#162]
比如我想在原有编辑器插件上增加一个面板
然后通过这个面板修改一些其它选项，目前有可能实现吗？

**Comment by hyzx86** [comment]
好多东西没有导出来。。虽然编辑器显示存在，但是运行不起来


```
import { getEventControlConfig } from 'amis-editor/dist/util';
// import { BaseEventContext } from 'amis-editor/dist/plugin';
// import { SelectControlPlugin, BaseEventContext } from 'amis-editor'; 
```

**Comment by hyzx86** [comment]
比如 SelectControlPlugin ，这个对象 无法在开发环境导入，会报 路径下这个东西不存在

 Can't resolve 'amis-editor/dist/plugin/Form/Select' 

如果我把代码 拷贝出来，需要调用这个东西 ，`getEventControlConfig` 代码引入没问题
运行就报 不存在。。

**Comment by hyzx86** [comment]
https://github.com/aisuda/amis-editor-demo/issues/143

**Comment by wibetter** [comment]
amis-editor中的大部分元素，都是可以通过扩充plugin的形式进行定制和改造的，但目前并未对amis-editor进行开源，对外部用户定制成本较高。

**Comment by hyzx86** [comment]
嗯。已经发现了一个折衷办法。就是类似于 CRUD 的组件封装
在现有组件外层增加一层包装作为自定义组件
