### ISSUE TITLE
分页功能怎么使用？

### ISSUE THREAD

**Issue by great-linux** [aisuda/amis-editor-demo#164]
想问一下分页怎么使用，设置好了不能点击，文档写的不是很详细。

**Comment by wibetter** [comment]
分页组件不能单独使用，一般用于实现纯前端分页功能的（通过接口一次性获取所有数据，在前端进行分页），可内嵌CRUD组件。比如：
<img width="514" alt="image" src="https://user-images.githubusercontent.com/11958920/205039406-e60e8ef9-92dd-429d-a19b-bb2bfe412718.png">
