### ISSUE TITLE
编辑器在移动端模式下标签页组件操作异常

### ISSUE THREAD

**Issue by AxeMea** [aisuda/amis-editor-demo#165]
编辑器在移动端模式下，  tabs 标签页组件无法拖入其他组件

**Comment by wibetter** [comment]
在这里试一下能否复现你说的问题，https://aisuda.github.io/amis-editor-demo/#/edit/0

**Comment by AxeMea** [comment]
> 在这里试一下能否复现你说的问题，https://aisuda.github.io/amis-editor-demo/#/edit/0

可以复线

**Comment by wibetter** [comment]
刚试了一下是可以正常拖入的，不知道你是怎么操作的，方便的话录屏看看。
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/11958920/203247064-a548a707-0b6c-4449-9741-0dcfa997179b.png">
