### ISSUE TITLE
vue3+vite "amis-ui/lib/components/ColorPicker" is not supported

### ISSUE THREAD

**Issue by kiananekocharm** [aisuda/amis-editor-demo#167]
![image](https://user-images.githubusercontent.com/56387127/200273559-77d51050-83b8-4e38-b183-6a0d043f0385.png)
![image](https://user-images.githubusercontent.com/56387127/200273695-1d9ebdaf-371c-4349-a362-fb544317b69c.png)

vue3，vite创建的项目使用amis-editor会报图里的错误

**Comment by wibetter** [comment]
1、amis-editor版本号？
2、如果使用amis-editor的？

**Comment by wibetter** [comment]
请将amis和amis-editor相关模块升级到最新版本。
