### ISSUE TITLE
选择图标弹窗 图标是空的 无法选择

### ISSUE THREAD

**Issue by zhjike0801** [aisuda/amis-editor-demo#168]
![1669695062798](https://user-images.githubusercontent.com/9379555/204436882-a0e084de-4860-4a8f-bf53-1d39a21ae0b4.png)

怎么将图标加进去，可以进行选择

**Comment by wibetter** [comment]
单独使用amis-editor暂不支持图标选择功能，目前仅在爱速搭平台支持。

**Comment by relaxing0314** [comment]
图标列表数据有什么办法可以自己插入吗？目前这样无法选择图标很影响使用感
