### ISSUE TITLE
  Can't resolve `vertx` 

### ISSUE THREAD

**Issue by 123456dengting** [aisuda/amis-editor-demo#174]
**npm run dev 时报错  Can't resolve `vertx` in file [/node_modules/mpegts.js/dist/mpegts.js], did you miss `npm install vertx`?**

**Comment by wibetter** [comment]
这个报错不影响服务启动。
启动amis-editor-demo的方式：
1、先执行 npm run start，启动成功后会自动打开一个页面，如果是第一次使用，打开的页面是没有内容的（需要再执行第二步）；
2、执行 npm run dev，执行成功后，刷新第一步打开的页面，即可看到最新的内容了。
