### ISSUE TITLE
多次执行 Editor.js 重复注册

### ISSUE THREAD

**Issue by atliwen** [aisuda/amis-editor-demo#175]
Error: The renderer with name "bat-editor" has already exists, please try another name!

![image](https://user-images.githubusercontent.com/10055836/210502843-614752b2-4609-42af-93da-379dd0f84e5e.png)

打断点调试看是重复注册了，但是我全文搜索了就只有一个地方使用了 amis
做了清除处理，  就剩下一行代码 
import {Editor, ShortcutKey} from "amis-editor";

**Comment by atliwen** [comment]
![image](https://user-images.githubusercontent.com/10055836/210503802-bae5f278-2284-4d98-9f91-e18312982a62.png)

**Comment by zhangdangit123** [comment]
遇到同样问题 amis:2.7.2 ,amis-editor:5.2.3-beta.12

**Comment by wibetter** [comment]
运行报错问题已在最新代码中修复（amis-editor-demo前端工程换成webpack实现），请拉取最新代码运行。

**Comment by zhanggq1014** [comment]
> ![image](https://user-images.githubusercontent.com/10055836/210503802-bae5f278-2284-4d98-9f91-e18312982a62.png)

请问你解决了吗
