### ISSUE TITLE
按照官方文档启动后

### ISSUE THREAD

**Issue by iceqing** [aisuda/amis-editor-demo#178]
```
npm i 
npm run dev
npm start
```
启动后点击编辑按钮，页面一直加载中
<img width="500" alt="image" src="https://user-images.githubusercontent.com/39587710/212836724-d0cdb2b4-a2be-4a98-854c-acae006f5a8f.png">

**Comment by YuDaiYan** [comment]
"amis-editor": "^5.2.3-beta.16",
"amis-editor-core": "^5.2.3-beta.16", 
会安装 5.2.3 版本，导致 Cannot find module `node_modules/amis-theme-editor/lib/renderers.css` 。
 改为     
"amis-editor": "5.2.3-beta.16",
"amis-editor-core": "5.2.3-beta.16",

**Comment by iceqing** [comment]
@YuDaiYan 试了下可以解决问题，非常感谢
