### ISSUE TITLE
项目无法启动，各种提示缺包

### ISSUE THREAD

**Issue by seantech2000** [aisuda/amis-editor-demo#179]
怎么搞的，死活无法启动，一下缺tslib，装了又缺一大堆
`
 [WARNI] Can't resolve `moment` in file [/node_modules/amis-ui/lib/components/calendar/YearsView.js], did you miss `npm install moment`?
.
 [WARNI] Can't resolve `moment` in file [/node_modules/amis-ui/lib/components/calendar/MonthsView.js], did you miss `npm install moment`?
.
 [WARNI] Can't resolve `moment` in file [/node_modules/amis-ui/lib/components/calendar/TimeView.js], did you miss `npm install moment`?

 [WARNI] Can't resolve `lodash/merge` in file [/node_modules/amis-ui/lib/components/calendar/TimeView.js], did you miss `npm install lodash`?

 [WARNI] Can't resolve `downshift` in file [/node_modules/amis-ui/lib/components/calendar/TimeView.js], did you miss `npm install downshift`?
.
 [WARNI] Can't resolve `moment` in file [/node_modules/amis-ui/lib/components/calendar/QuartersView.js], did you miss `npm install moment`?
.
 [WARNI] Can't resolve `match-sorter` in file [/node_modules/amis-ui/lib/components/InputBoxWithSuggestion.js], did you miss `npm install match-sorter`?

`

**Comment by wibetter** [comment]
该问题已在最新代码中修复（amis-editor-demo前端工程换成webpack实现），请拉取最新代码运行。
