### ISSUE TITLE
升级编辑器到5.2.3 提示找不到依赖

### ISSUE THREAD

**Issue by minzhenyu** [aisuda/amis-editor-demo#180]
报错如下：
This dependency was not found:

* amis-editor/dist/style.css in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./package/plugin/component/editor.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save amis-editor/dist/style.css

问题：
以前
import 'amis-editor/dist/style.css';
import {Editor} from "amis-editor";
看了node_modules/amis-editor下确实没有dist了，

是不是新版本不需要这么引入了，新版本应该怎么使用？

**Comment by minzhenyu** [comment]
@nwind

**Comment by relaxing0314** [comment]
需要将import 'amis-editor/dist/style.css';改为import 'amis-editor-core/lib/style.css';
