### ISSUE TITLE
升级编辑器导致报错 The renderer with name "bat-editor" has already exists, please try another name!

### ISSUE THREAD

**Issue by minzhenyu** [aisuda/amis-editor-demo#181]
升级前：
"amis": "1.9.0-beta.12",
 "amis-editor": "^4.1.0-beta.2",

升级后：
 "amis": "^2.7.2",
  "amis-core": "^2.7.2",
  "amis-editor": "^5.2.3",
  "amis-ui": "^2.7.2",

报错：
The renderer with name "bat-editor" has already exists, please try another name!
![image](https://user-images.githubusercontent.com/12856051/217707469-f80f5454-00e1-4b24-822e-7d52e2f25bca.png)
@wibetter 这个能麻烦看下是什么问题吗？

**Comment by minzhenyu** [comment]
![image](https://user-images.githubusercontent.com/12856051/217708355-d9ac7b23-5d03-471a-ab9f-672157949de3.png)
看了下是availableLanguages 这个遍历去注册语言导致的

**Comment by minzhenyu** [comment]
还有个问题请教下，编辑器哪个版本开始支持value 可以定义变量、联动其他数据的？

**Comment by wibetter** [comment]
先说一下你是怎么使用amis-editor，构建工具用的是什么，最好能贴下构建配置文件内容。

**Comment by littleee** [comment]
同样问题， 请问解决了吗？  使用create-react-app搭建的项目就能复现

**Comment by wibetter** [comment]
这里问题，你要确保用到的amis相关的包都支持esm，目前amis相关包的最新版本都支持esm，先尝试着将这些包升级到最新。
另外你要快捷处理这个问题的话，在webpack中处理下也行：resolve.conditionNames: ['require']，统一走commonjs模块。
