### ISSUE TITLE
第一次运行项目，报找不到模块

### ISSUE THREAD

**Issue by cy9865** [aisuda/amis-editor-demo#182]
npm i 安装依赖后，npm start 开服务，然后npm run dev 开始编译完就报这个错误了
Uncaught [ModJS] Cannot find module `node_modules/amis-theme-editor/lib/renderers.css`
![Snipaste_2023-02-10_09-42-16](https://user-images.githubusercontent.com/124946555/217979129-7c7b2fdb-3d00-49ed-a3e8-70995b6ce9cb.png)

**Comment by relaxing0314** [comment]
在配置文件fis-conf.js中配置fis.match('amis/**.js', {
	preprocessor: fis.plugin('js-require-css')
});下面添加配置fis.match('amis-editor/**.js', {
	preprocessor: fis.plugin('js-require-css')
});就可以了

**Comment by cy9865** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cy9865** [comment]
> 在配置文件fis-conf.js中配置fis.match('amis/**.js', { preprocessor: fis.plugin('js-require-css') });下面添加配置fis.match('amis-editor/**.js', { preprocessor: fis.plugin('js-require-css') });就可以了

解决了，谢谢

**Comment by freshhan163** [comment]
在配置文件，fis-conf.js配置文件中，添加代码
// fis-conf中的已有配置
fis.match('amis/**.js', {
    preprocessor: fis.plugin('js-require-css')
});

// 需要新增的配置，记得要加上 **！！！
fis.match('amis-editor/**.js', {
    preprocessor: fis.plugin('js-require-css')
})

**Comment by Yaya-20** [comment]
> 在配置文件，fis-conf.js配置文件中，添加代码 // fis-conf中的已有配置 fis.match('amis/**.js', { preprocessor: fis.plugin('js-require-css') });
> 
> // 需要新增的配置，记得要加上 **！！！ fis.match('amis-editor/**.js', { preprocessor: fis.plugin('js-require-css') })

加上这个配置了， 还是没找到renderers.css

**Comment by cy9865** [comment]
> > 在配置文件，fis-conf.js配置文件中，添加代码 // fis-conf中的已有配置 fis.match('amis/**.js', { preprocessor: fis.plugin('js-require-css') });
> > // 需要新增的配置，记得要加上 **！！！ fis.match('amis-editor/**.js', { preprocessor: fis.plugin('js-require-css') })
> 
> 加上这个配置了， 还是没找到renderers.css

他强调了要加* *，但是好像被系统隐藏掉了，amis-editor/后面一定要加* *
![Snipaste_2023-02-21_11-20-37](https://user-images.githubusercontent.com/124946555/220239352-b2bd8705-5b51-423b-8ffd-de91996d3f93.png)

**Comment by Yaya-20** [comment]
![image](https://user-images.githubusercontent.com/67141479/220261070-ba7f7ad7-2117-4bc6-8a2f-4d276dbd7b88.png)
这两个配置都加上去了，还是加载不到css，  还需要配置啥吗，

**Comment by seantech2000** [comment]
> ![image](https://user-images.githubusercontent.com/67141479/220261070-ba7f7ad7-2117-4bc6-8a2f-4d276dbd7b88.png) 这两个配置都加上去了，还是加载不到css， 还需要配置啥吗，

没用的，解决不到！

**Comment by wibetter** [comment]
该问题已在最新代码中修复（amis-editor-demo前端工程换成webpack实现），请拉取最新代码运行。

**Comment by cy9865** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
