### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by zhsngq** [aisuda/amis-editor-demo#183]
![image](https://user-images.githubusercontent.com/12964696/218681774-ff21d044-d0b4-4878-8a06-803bf191e25e.png)
![image](https://user-images.githubusercontent.com/12964696/218681828-9cef2ed9-06f4-4834-abde-37830083776e.png)

**Comment by cloudroc** [comment]
同样的问题

**Comment by seantech2000** [comment]
确实跑步起来，申请的demo

**Comment by freshhan163** [comment]
参考ISSUE  “找不到模块”，修改一下fis-conf配置文件就行

**Comment by enkialtria** [comment]
我也是Uncaught [ModJS] Cannot find module `index.html`，请问你解决了吗？

**Comment by wibetter** [comment]
该问题已在最新代码中修复（amis-editor-demo前端工程换成webpack实现），请拉取最新代码运行。
