### ISSUE TITLE
amis-editor按钮配置项左右侧图标选择功能不能用

### ISSUE THREAD

**Issue by relaxing0314** [aisuda/amis-editor-demo#185]
"amis": "2.6.0",
    "amis-core": "2.6.0",
    "amis-editor": "5.2.3-beta.16",
    "amis-editor-core": "5.2.3-beta.16",
    "amis-formula": "2.6.0",
    "amis-ui": "2.6.0",
    "amis-widget": "^2.0.5",
有没有其他办法可以自己插入可选图标的数据呀？
![1676369564984](https://user-images.githubusercontent.com/39429166/218705507-bd8a801d-3b50-4ce5-a554-0a9a9c5a795f.png)

**Comment by wibetter** [comment]
amis-editor中的图标选择器暂不支持使用，目前仅在爱速搭中支持了。
