### ISSUE TITLE
vue2 里可以当组件调用吗？

### ISSUE THREAD

**Issue by jin516** [aisuda/amis-editor-demo#186]
我想用于vue项目调用组件和本地项目组件混合使用，这个可以吗？

**Comment by jin516** [comment]
> 是说在vue项目中使用amis-editor吗？

是的，我想在vue项目里实现拖拽组件，生成的json自动存到数据库，调用出来渲染

**Comment by jin516** [comment]
> > 是说在vue项目中使用amis-editor吗？
> 
> 是的，我想在vue项目里实现拖拽组件，生成的json自动存到数据库，调用出来渲染

现在就是不知道怎么集成到vue项目中

**Comment by wibetter** [comment]
amis-editor是react技术栈项目，如果需要在vue中使用，可以尝试使用vuera。
