### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by enkialtria** [aisuda/amis-editor-demo#187]
Uncaught [ModJS] Cannot find module `index.html` 如何解决呀

**Comment by github-zhang** [comment]
download 压缩包

**Comment by citynook** [comment]
amis2.6版本没有此问题，升级2.6+后会出现，按如下方法可解决：

修改fis-conf.js，在代码
fis.hook('node_modules', {
上面增加一行：
fis.unhook('components');

完整代码如下：
fis.unhook('components');
fis.hook('node_modules', {
    shimProcess: false,
    shimGlobal: false,
    shimBuffer: false
});

经测试，升级到2.8可以正常运行。

**Comment by wibetter** [comment]
该问题已在最新代码中修复（amis-editor-demo前端工程换成webpack实现），请拉取最新代码运行。
