### ISSUE TITLE
自定义组件分类排序的规则是什么？

### ISSUE THREAD

**Issue by lhkg1988** [aisuda/amis-editor-demo#189]
想给自定义组件的分类排个序，现在卡不出来排序是按照什么规则来的？
<img width="292" alt="image" src="https://user-images.githubusercontent.com/7578173/223933954-0eb59e47-8940-4b6e-8e29-981e8e2b185f.png">

**Comment by lhkg1988** [comment]
tags的排序规则

**Comment by wibetter** [comment]
分类暂时不支持自定义排序，目前默认根据自定义组件排列顺序提取tags分类，如果你想将某个分类（A）设置在靠前展示，可以将该分类下面的自定义组件的order设置成较大数值（比如501、502、503...），如果还想讲分类B设置在分类A的后面，可以将分类A下面的自定义组件order设置成401、402、403...等。
