### ISSUE TITLE
amis-editor是否可以考虑使用CommonJS模块系统

### ISSUE THREAD

**Issue by hellozqy** [aisuda/amis-editor-demo#19]
amis-editor所采用的UMD模块方式在TS中需要在 tsconfig.json 中设置 compilerOptions.esModuleInterop 为 true来兼容UMD模式，但这个兼容会导致格式校验变得更加严格。

**Comment by 306392691** [comment]
也就是import React from 'react';改成import * as React from 'react';

**Comment by 2betop** [comment]
真正的代码其实不在这，当是个示例好了。

**Comment by 306392691** [comment]
![image](https://user-images.githubusercontent.com/48118280/88522468-f96a8b80-d028-11ea-92b4-7b6009d80dfb.png)

**Comment by 306392691** [comment]
但是如果直接引用的话就会导致报错，在amis-editor/dist/Editor下第1行和第6行报错。
![image](https://user-images.githubusercontent.com/48118280/88522670-49495280-d029-11ea-8b7b-3d20d4e4b23d.png)

**Comment by wibetter** [comment]
目前amis-editor（5.2.1-beta.32）支持 CommonJS 和 ESM 两种模式。
