### ISSUE TITLE
可以运行的，yeah

### ISSUE THREAD

**Issue by github-zhang** [aisuda/amis-editor-demo#190]
nodejs >=14.15.0 

[https://github.com/aisuda/amis-editor-demo/pull/188/commits/bf4effc25d3ee1411d515d51fb29e03467f30ee2](https://github.com/aisuda/amis-editor-demo/pull/188/commits/bf4effc25d3ee1411d515d51fb29e03467f30ee2)    找不到css 文件

[https://github.com/aisuda/amis-editor-demo/issues/187](https://github.com/aisuda/amis-editor-demo/issues/187)  找不到 index html

**Comment by liangxp** [comment]
然并暖，没人的

**Comment by wibetter** [comment]
该问题已在最新代码中修复（amis-editor-demo前端工程换成webpack实现），请拉取最新代码运行。
