### ISSUE TITLE
样式崩溃

### ISSUE THREAD

**Issue by zhanggq1014** [aisuda/amis-editor-demo#192]
![image](https://user-images.githubusercontent.com/54018170/225834886-f2ee598c-de28-4010-beab-ea6556c1808b.png)
最新版的amis-editor，请问怎么引入样式

**Comment by zhanggq1014** [comment]
![image](https://user-images.githubusercontent.com/54018170/225835080-cd5d3177-1e5a-4c5c-b874-bb1456170d7f.png)

**Comment by wibetter** [comment]
引进editor的样式：
import 'amis-editor-core/lib/style.css';
