### ISSUE TITLE
重要通知！amis-editor已开源！

### ISSUE THREAD

**Issue by wibetter** [aisuda/amis-editor-demo#194]
amis-editor包含两个模块：amis-editor-core、amis-editor，其中amis-editor-core存放页面编辑器的核心模块，amis-editor存放编辑器中的各类插件（plugin：含130+内置组件的基本信息、属性配置、和组件相关的各类交互实现）。

amis-editor源码位置：https://github.com/baidu/amis/tree/master/packages/amis-core
amis-editor-core源码位置：https://github.com/baidu/amis/tree/master/packages/amis-editor-core

**Comment by liangxp** [comment]
有关于editor 编译  打包 相关的开发手册么？祝amis越来越火

**Comment by wibetter** [comment]
@liangxp  editor源码已经开放了，打包工具可以自选，你可以选webpack、rollup、vite等。

**Comment by StringKe** [comment]
@wibetter amis-theme-editor 这个开源了吗？

**Comment by wibetter** [comment]
amis-theme-editor 暂时没有开源计划。

**Comment by StringKe** [comment]
> amis-theme-editor 暂时没有开源计划。

目前这个包内组件在使用时会有错误，应该如何修复呢？

**Comment by wibetter** [comment]
@StringKe  先截图看下是什么报错？

**Comment by StringKe** [comment]
> @StringKe 先截图看下是什么报错？

![CleanShot 2023-04-06 at 14 16 36@2x](https://user-images.githubusercontent.com/31089228/230287704-2030a47e-4e8e-4807-b226-39065299fb85.png)

任意 fromitem 修改 border 时候出现

**Comment by xumx** [comment]
这包里没有英文选项？packages/amis-editor/ 里面怎么改都改不过来，不听appLocale的设置

**Comment by wibetter** [comment]
@StringKe 这个问题需要等amis发新版，

**Comment by gland2015** [comment]
牛逼
