### ISSUE TITLE
UMI4 集成amis-editor5.2.5-beta.5，浏览表单代码时浏览器控制台报错Uncaught SyntaxError: Unexpected token '<' 

### ISSUE THREAD

**Issue by liuzyong** [aisuda/amis-editor-demo#196]
![image](https://user-images.githubusercontent.com/33834517/227405009-30355a4d-4a26-4178-86c1-abca8bd87df8.png)

**Comment by wibetter** [comment]
看下能不能在这里复现：https://aisuda.github.io/amis-editor-demo/#/edit/0

**Comment by wibetter** [comment]
初步判断是构建类问题，如webpack配置问题。看报错，应该是左侧代码面板没有正常加载，请参考amis-editor-demo使用尝试使用monaco-editor-webpack-plugin解决。
