### ISSUE TITLE
新版本的包page组件用css属性写的css类会被自动转换成错误的格式

### ISSUE THREAD

**Issue by wobudapai** [aisuda/amis-editor-demo#198]

**Comment by zycfj** [comment]
![image](https://user-images.githubusercontent.com/16100274/228428112-59632462-82b8-46eb-af58-2b6966143f87.png)

**Comment by Icodezhan** [comment]
@2betop @wibetter @nwind @blackmady @taosher

**Comment by wibetter** [comment]
截图看下你用css属性写的是什么，最好发一下完整的json。

**Comment by Icodezhan** [comment]
> 截图看下你用css属性写的是什么，最好发一下完整的json。

这样子，随便一个样式都会 @wibetter 
![微信图片_20230404144414](https://user-images.githubusercontent.com/45064164/229710139-a4748df3-ce04-4894-affa-eaffd5f167be.png)

**Comment by zycfj** [comment]
> 

随便写个css都会出问题

**Comment by wibetter** [comment]
@Icodezhan 咱不建议手动再css中写自己的class，目前amis-editor还没有支持页面级自定义css。

**Comment by Icodezhan** [comment]
> @Icodezhan 咱不建议手动再css中写自己的class，目前amis-editor还没有支持页面级自定义css。

@wibetter 
可是以前是可以的呀，官方文档也说可以的，那升级版本后就不行了，那岂不是之前写的json都废了？不带这样的吧？
![微信图片_20230406131020](https://user-images.githubusercontent.com/45064164/230277578-99325cb5-dfaf-49d9-a1df-6f337b786972.png)

**Comment by Icodezhan** [comment]
> > @Icodezhan 咱不建议手动再css中写自己的class，目前amis-editor还没有支持页面级自定义css。
> 
> @wibetter 可是以前是可以的呀，官方文档也说可以的，那升级版本后就不行了，那岂不是之前写的json都废了？不带这样的吧？ ![微信图片_20230406131020](https://user-images.githubusercontent.com/45064164/230277578-99325cb5-dfaf-49d9-a1df-6f337b786972.png) ![图片](https://user-images.githubusercontent.com/45064164/230277858-f4298033-6ddf-4b2a-bcb4-b8f294bc1ad0.png)

@wibetter 求求把自定义css功能加回来吧，这个很好用啊

**Comment by zycfj** [comment]
> @Icodezhan 咱不建议手动再css中写自己的class，目前amis-editor还没有支持页面级自定义css。

确定以前是支持的，最近应该是BUG导致解析错误了。麻烦修复下吧，这个功能需求应该不少

**Comment by Icodezhan** [comment]
> @Icodezhan 咱不建议手动再css中写自己的class，目前amis-editor还没有支持页面级自定义css。

现在虽然格式变错误了，但是实际上css是有生效的，只是格式错了就不能再次编辑了，以前是好的

**Comment by Icodezhan** [comment]
@qkiroc @wibetter 正常的逻辑是把自动生成的.myClass属性隐藏起来，而不是把css属性隐藏起来，把page的css属性隐藏起来后就没办法编辑了，我升级到最新版编辑器后以前写的json都出问题了
![mmexport1680840313303.png](https://user-images.githubusercontent.com/45064164/230540035-8a0ed745-b851-4aac-b722-ee01e35de6fd.png)

![mmexport1680840311446.png](https://user-images.githubusercontent.com/45064164/230540050-0876663b-8d32-4661-87ff-e9a9e2f58900.png)

**Comment by wibetter** [comment]
已修复，请使用最新amis-editor、amis-editor-core版本：5.2.5-beta.7。

**Comment by Icodezhan** [comment]
> 已修复，请使用最新amis-editor、amis-editor-core版本：5.2.5-beta.7。

好像并没有修复，即使我删除了node_modules，更新amis-editor、amis-editor-core版本为5.2.5-beta.7，重新下载依赖，然后我再使用page自定义css，保存后依旧会将page的css属性隐藏了，无法再次找到css属性进行编辑

**Comment by wibetter** [comment]
https://github.com/baidu/amis/issues/6555#issuecomment-1503168132
