### ISSUE TITLE
新版本编辑器所有组件的外观，边框第一个下拉框点击后会报错

### ISSUE THREAD

**Issue by Icodezhan** [aisuda/amis-editor-demo#199]
新版本编辑器所有组件的外观，边框第一个下拉框点击后会报错

![微信图片_20230404155420](https://user-images.githubusercontent.com/45064164/229726104-50868ad1-b883-4481-bc45-c9b25d80ed7f.png)
![微信图片_20230404155444](https://user-images.githubusercontent.com/45064164/229726117-afe8e29c-a03a-463b-8a77-75e235ef85c0.png)

**Comment by Icodezhan** [comment]
@2betop @wibetter @nwind @blackmady @taosher

**Comment by StringKe** [comment]
这个组件来自amis-theme-editor 但是似乎没有开源

**Comment by wibetter** [comment]
这个问题已在amis中修复，需要等amis发新版。

**Comment by wibetter** [comment]
升级版本后可正常使用：
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/11958920/236723902-3024a95e-9197-4f88-996c-8d69524f1ceb.png">

**Comment by Icodezhan** [comment]
> 升级版本后可正常使用：
> <img width="1393" alt="image" src="https://user-images.githubusercontent.com/11958920/236723902-3024a95e-9197-4f88-996c-8d69524f1ceb.png">
> 

我在自己项目里升级了版本后还是不行，在这个amis-editor-demo项目是可以的，我看是更新了其中demo文件夹的内容，有点疑问，这部分为何不一起打包到npm，如果我在其他项目要使用amis-editor那这个demo文件夹里的东西我应该如何引入？

**Comment by Icodezhan** [comment]
> 升级版本后可正常使用： <img alt="image" width="1393" src="https://user-images.githubusercontent.com/11958920/236723902-3024a95e-9197-4f88-996c-8d69524f1ceb.png">

破案了，yarn的锅，yarn安装不到最新版的amis-theme-editor、amis-theme-editor-helper，要npm才行

**Comment by wibetter** [comment]
跟用yarn没有关系，最重要的是amis-editor用到的amis-theme-editor、amis-theme-editor-helper已发版本，之前是因为没有发布对应的新版本。

**Comment by Icodezhan** [comment]
> 跟用yarn没有关系，最重要的是amis-editor用到的amis-theme-editor、amis-theme-editor-helper已发版本，之前是因为没有发布对应的新版本。

npm官网最新的是2.0.11-beta.2
![图片](https://github.com/aisuda/amis-editor-demo/assets/45064164/cd38029c-7d03-4b6a-8415-6eec96d6b173)
而yarn官网最新的是2.0.10
![图片](https://github.com/aisuda/amis-editor-demo/assets/45064164/a7537a00-d350-4eba-95d9-565c30a8e6cc)

即使现在，如果我用yarn只能拉取到2.0.10，要用npm才能拉取到2.0.11-beta.2

**Comment by wibetter** [comment]
@Icodezhan NPM扩展包和NPM自定义组件主要在爱速搭平台中使用，当然也指出私有化部署版中使用，如果支持单独扩展编辑器自定义组件，仅使用amis-widget即可，无需发布成NPM包。
