### ISSUE TITLE
无法启动项目，运行项目报错

### ISSUE THREAD

**Issue by aaaawy** [aisuda/amis-editor-demo#203]
npm run dev时：
[WARNI] Can't resolve `rc-input-number/lib/utils/MiniDecimal` in file [/node_modules/amis-ui/lib/components/NumberInput.js], did you miss `npm install rc-input-number`?
[WARNI] Can't resolve `vertx` in file [/node_modules/mpegts.js/dist/mpegts.js], did you miss `npm install vertx`?
安装以上两个包还是会发出同样警告
npm run start时:
浏览器报错：Uncaught [ModJS] Cannot find module `rc-input-number/lib/utils/MiniDecimal`

**Comment by wibetter** [comment]
请拉取amis-editor-demo最新代码运行，旧版示例不再维护。
