### ISSUE TITLE
增删改查组件，按钮添加点击事件报错

### ISSUE THREAD

**Issue by lengthy-daydream** [aisuda/amis-editor-demo#204]
增删改查组件，按钮添加点击事件报错
![image](https://user-images.githubusercontent.com/58502519/231999996-615c651a-1efd-424b-92c9-426c1029787d.png)

**Comment by lengthy-daydream** [comment]
单独添加的按钮事件可以点击
![image](https://user-images.githubusercontent.com/58502519/232009669-d39d052d-6841-484a-a4f7-d5da7bdfcca4.png)
增删改查生成的按钮，少了这个代码：

"onEvent": {
    "click": {
      "actions": [
      ]
    }

![image](https://user-images.githubusercontent.com/58502519/232009738-b828c3dd-ec1d-4cc7-b88c-4c02b7bde777.png)

**Comment by wibetter** [comment]
无法复现：
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/11958920/233817204-307b484c-94b4-4aa5-9cdb-e4a6005108db.png">

请尝试将amis-editor和amis升级到最新版本。
