### ISSUE TITLE
自定义组件扩展问题

### ISSUE THREAD

**Issue by summmer-is-hot** [aisuda/amis-editor-demo#208]
项目中目前只能使用@Renderer扩展自定义渲染组件，
使用@FormItem扩展自定义表单组件支持吗，amis那边是支持的，在这个项目中使用有报错

**Comment by wibetter** [comment]
amis-editor-demo中的自定义组件示例就是这么写的：
<img width="997" alt="image" src="https://github.com/aisuda/amis-editor-demo/assets/11958920/c510fea6-f761-492a-b722-c6fbf0fc0dba">
确认下代码是不是写的不对。

**Comment by zwlyn** [comment]
请问下自定义组件后如何将包含该自定义组件的amis-editor-demo生成的json运用于具体的项目中，会出现Error: 找不到对应的渲染器的报错，请问下如何通过amis-editor-demo生成相应的依赖解决该问题？

**Comment by wibetter** [comment]
运行环境渲染方式，可以参考这里的实现：
<img width="989" alt="image" src="https://github.com/aisuda/amis-editor-demo/assets/11958920/b2310eba-03dd-499e-8e2c-bcff921d2f5b">

如果有自定义组件，这里也需要额外引入自定义组件渲染器。
