### ISSUE TITLE
请问在amis-editor-demo里面怎么修改接口请求的方法fetcher，因为要注入接口请求的鉴权信息到header？

### ISSUE THREAD

**Issue by BarronLin** [aisuda/amis-editor-demo#209]
## 请问在amis-editor-demo里面怎么修改接口请求的方法fetcher，因为要注入接口请求的鉴权信息到header

**Comment by wibetter** [comment]
amis-editor-demo的fetcher实现是在这里，你们可以在这里自定义：
<img width="1126" alt="image" src="https://github.com/aisuda/amis-editor-demo/assets/11958920/1611e450-ff1e-4980-91f6-34839a0d62a6">
