### ISSUE TITLE
amis-editor 左侧的代码编辑器，可以指定宽度吗？

### ISSUE THREAD

**Issue by hq5544** [aisuda/amis-editor-demo#28]
请问 amis-editor 左侧的代码编辑器，可以指定宽度吗？
目前给出的宽度太小了，如果页面复杂，嵌套层数很多，需要频繁横向滚动，不是太方便。
希望能够传入 props 配置。

**Comment by 2betop** [comment]
左边代码面板的宽度是可以动态改变的，怀疑你用的还是旧版本

**Comment by hq5544** [comment]
> 左边代码面板的宽度是可以动态改变的，怀疑你用的还是旧版本

果然是的。1.0.11 版本可以拖拽调整宽度了。
但是 1.0.12 版本，在我的项目里会报错。

**Comment by wibetter** [comment]
Editor左侧代码面板宽度可拖拽。
请使用新版Editor，目前已升级至4.1.0-beta.24。
