### ISSUE TITLE
找不到依赖 , "@fex/amis-editor": "0.0.55",

### ISSUE THREAD

**Issue by MrStrangeBao** [aisuda/amis-editor-demo#3]
找不到依赖这个在Npm上, "@fex/amis-editor": "0.0.55".

**Comment by FatDong1** [comment]
这个没有开源

**Comment by MrStrangeBao** [comment]
哦

**Comment by PengXing** [comment]
@2betop 请问，`@fex/amis-editor` 有开源计划吗？

**Comment by 2betop** [comment]
改名叫 amis-editor 外部也能使用了，用法见 readme https://github.com/fex-team/amis-editor

**Comment by wibetter** [comment]
外部 不存在 @fex/前缀相关的 包，带这个前缀的报仅百度内网可用。
