### ISSUE TITLE
请问一下amis-editor 搭建完后，怎么打包成amis-admin?

### ISSUE THREAD

**Issue by Rock-liyi** [aisuda/amis-editor-demo#31]

**Comment by vjiuzhou** [comment]
> _No description provided._

https://gitee.com/uniappadmin/uniappadmin  用这个就可以打包成amis-admin

**Comment by wibetter** [comment]
amis-editor 搭建完后生成的json，可参考 amis-editor-demo/component/AMISRenderer.tsx 进行 render。
