### ISSUE TITLE
请问跨域问题如何解决

### ISSUE THREAD

**Issue by Rock-liyi** [aisuda/amis-editor-demo#32]
![image](https://user-images.githubusercontent.com/35133768/90953575-08fdb880-e49f-11ea-9ef0-adab2cc3df95.png)

**Comment by rencoo** [comment]
可以通过改写ajax请求，让请求打到同源的服务器上，然后进行转调

**Comment by wibetter** [comment]
单独使用amis-editor出现跨域问题，需要在接口端支持跨域请求（CORS）。

**Comment by zwlyn** [comment]
请问可以通过配置前端webpack的proxy解决吗，或amis.config.js中支持相关的代理配置吗？
