### ISSUE TITLE
【BUG】编辑器选中某个组件后按"X"会删除该组件

### ISSUE THREAD

**Issue by feizhen** [aisuda/amis-editor-demo#33]
使用在线编辑器编辑组件，选中某个组件后按下 'x' ，该组件会被删除：
![image](https://user-images.githubusercontent.com/11854027/91031915-cf11eb00-e633-11ea-90fc-b29c5fefe38b.png)

![image](https://user-images.githubusercontent.com/11854027/91032012-f36dc780-e633-11ea-976a-cff131e69560.png)

**Comment by wibetter** [comment]
amis-editor提供的快捷键功能，目前已更新并支持以下快捷键功能：
<img width="551" alt="image" src="https://user-images.githubusercontent.com/11958920/205201156-26292d63-83e5-454f-b34a-b92f8353da84.png">
