### ISSUE TITLE
开源计划（Open source work plan）

### ISSUE THREAD

**Issue by ganyanchuan1989** [aisuda/amis-editor-demo#47]
是否有开源计划？还是未来也会一直不开源呢？一个不开源得又不收费得软件，别说商用了，自己使用都不敢。万一遇到问题就卡脖子了

**Comment by ganyanchuan1989** [comment]
自己花了几天时间撸了一个demo，感觉这个实现起来技术难度不大，主要是业务场景需要适配比较麻烦。
https://github.com/ganyanchuan1989/react-visualization-demo

欢迎加V一起技术交流
![Uploading 微信图片_20201130172202.jpg…]()

**Comment by wibetter** [comment]
[README.md](https://github.com/aisuda/amis-editor-demo#readme)中已经说了，免费使用（包括商用）：
![image](https://user-images.githubusercontent.com/11958920/169731248-e0158c6a-2181-4e16-aaec-421cc9550783.png)
