### ISSUE TITLE
amis-editor-demo 如何打包并部署呢？

### ISSUE THREAD

**Issue by Mlijianye** [aisuda/amis-editor-demo#48]
我想在服务器端部署一个可视化编辑器并且嵌入，但是不知道怎么打包并且发布

**Comment by belongwqz** [comment]
前端小白，同问

**Comment by shuracwf** [comment]
同问+1

**Comment by a775611** [comment]
直接把可视化编辑器嵌到可以打包的项目中,再部署到服务器端

**Comment by wy1009** [comment]
我也想知道……不想重复写代码了，只想直接把 demo 部署一下。打个包的事，这么难的吗……

**Comment by break60** [comment]
打包部署问题你们解决了么

**Comment by fxwing** [comment]
webpack打包出一堆js文件  怎么解决下呢

**Comment by rencoo** [comment]
> 我也想知道……不想重复写代码了，只想直接把 demo 部署一下。打个包的事，这么难的吗……

我这边拿官方的改了下，可以满足部署需求
https://github.com/rencoo/amis-editor-deploy

**Comment by rencoo** [comment]
> <img alt="@wy1009" width="40" height="40" src="https://avatars.githubusercontent.com/u/18343973?s=88&amp;u=e1be96eb071d1d09c09bf313f893adbeba3c8f29&amp;v=4">

我这边拿官方的改了下，可以满足部署需求
https://github.com/rencoo/amis-editor-deploy

**Comment by rencoo** [comment]
> 打包部署问题你们解决了么

我这边拿官方的改了下，可以满足部署需求
https://github.com/rencoo/amis-editor-deploy

**Comment by wibetter** [comment]
amis-editor单独使用和打包方式，可参考[amis-widget](https://github.com/aisuda/amis-widget)。
