### ISSUE TITLE
点击右上角的全部导出没有反应

### ISSUE THREAD

**Issue by Jetereting** [aisuda/amis-editor-demo#5]
点击右上角的全部导出没有反应
![image](https://user-images.githubusercontent.com/11585188/69809424-b0a5cd00-1224-11ea-8b62-f0c3d2c7b81f.png)

**Comment by zhylmzr** [comment]
@Jetereting 这个导出还没完成. Tips 的样式有问题导致看不到
![Xnip2019-12-09_15-51-41](https://user-images.githubusercontent.com/15730824/70417269-d8eec080-1a9b-11ea-8d9e-60fc5897d4b2.jpg)

**Comment by 2betop** [comment]
这个先在编辑模式下，手动 copy page 级别的 schema 吧，可能最近都没时间处理这个。人手不够

**Comment by YQMMKINGDOM** [comment]
解决了么？为什么我还是无法全部导出？

**Comment by wibetter** [comment]
全部导出功能只是一个静态展示按钮，目前还未支持导出功能。

**Comment by eAtmApp** [comment]
去开发工具中复制localstorage  -_-!
