### ISSUE TITLE
使用 npm run gh-pages 后生成的 静态文件中 引用的css 和 js 并非本地的，还是cdn上的资源

### ISSUE THREAD

**Issue by bluehr** [aisuda/amis-editor-demo#51]
ps : 后端一枚不太懂前端，如果描述有问题还请见谅
index.html 中引用了许多 https://bce.bdstatic.com/* 
实际上我发现在本地的 gh-pages/n/amis-editor/node_modules/mobx-react/dist  以及 gh-pages/pkg文件夹中都有这些js和 css

**Comment by belongwqz** [comment]
可以在fis-conf.js里修改为你想要的地址。

**Comment by bluehr** [comment]
> 可以在fis-conf.js里修改为你想要的地址。

@belongwqz   woo~ it works 非常感谢

**Comment by bluehr** [comment]
@belongwqz 替换成公网地址确实是可行的，不过现在比较尴尬的是替换成相对路径会有问题 ，
- 打包后的gh-pages/index.html 和gh-pages/pkg/style_15cb566.css 引用的是相同的相对路径
还得手动调整其中一个才行，这个问题有办法控制吗，大佬

**Comment by belongwqz** [comment]
> @belongwqz 替换成公网地址确实是可行的，不过现在比较尴尬的是替换成相对路径会有问题 ，
> 
> * 打包后的gh-pages/index.html 和gh-pages/pkg/style_15cb566.css 引用的是相同的相对路径
>   还得手动调整其中一个才行，这个问题有办法控制吗，大佬

@bluehr 是有这个问题，我是直接将html文件改正确来使用。

**Comment by bluehr** [comment]
@belongwqz 老哥，能给个微信吗，关于这个amis-editor想请教您一两个本地部署的问题。

**Comment by belongwqz** [comment]
> @belongwqz 老哥，能给个微信吗，关于这个amis-editor想请教您一两个本地部署的问题。

我也是个半吊子，嘿嘿，微信就是github里的名称了。
