### ISSUE TITLE
在自己的项目中引入amis-editor，样式崩了。。

### ISSUE THREAD

**Issue by iceycc** [aisuda/amis-editor-demo#53]
项目使用的antd pro生成的，用 `npm install emis-editor`安装
页面引入
```jsx
import React from 'react';
import {Editor} from 'amis-editor';
import 'amis-editor/dist/style.css'

export default () => {
  // const props = {}
  return (
    <Editor style={{width: '100%', height: '100%'}}/>
  );
};
```
然后样式乱了

**Comment by RaconXXY** [comment]
老哥你解决了嘛，我也遇到了这个问题

**Comment by gaving-mx** [comment]
<link rel="stylesheet" href="font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="bootstrap/dist/css/bootstrap.css" />
        
        <link rel="stylesheet" href="amis/lib/themes/default.css" />
        <link rel="stylesheet" href="amis-editor/dist/style.css" />

**Comment by wibetter** [comment]
请使用新版amis-editor（5.2.1-beta.31），目前样式文件路径是：amis-editor-core/lib/style.css。
