### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by miwoy** [aisuda/amis-editor-demo#58]
直接编译运行报错：
Uncaught [ModJS] Cannot find module `mobx-state-tree`
手动安装`mobx-state-tree`后报错：
Uncaught TypeError: mobx.makeObservable is not a function
mobx-state-tree应该使用哪个版本，package.json里并没有说明

**Comment by hotlong** [comment]
+1

**Comment by hotlong** [comment]
测试下来要用npm i就没问题，yarn各种错

**Comment by miwoy** [comment]
@hotlong 你使用npm i 就可以了吗？我这还是不行

**Comment by wibetter** [comment]
目前amis-editor使用的是"mobx-state-tree": "^3.17.3"。
