### ISSUE TITLE
Bug反馈  按钮组死循环 必现

### ISSUE THREAD

**Issue by liuarui** [aisuda/amis-editor-demo#70]
复现方式：
1. 创建一个新页面
2. 添加增删改查组件
3. 新增一列按钮组
4. 在按钮组后追加一个按钮组
5. 报错，造成死循环

**Comment by wibetter** [comment]
请使用新版Editor，目前已升级至4.1.0-beta.24。
![image](https://user-images.githubusercontent.com/11958920/169732500-1b8af2e4-0fe4-4820-962f-068e03f3dd21.png)
