### ISSUE TITLE
自定义组件无法选择具体分类

### ISSUE THREAD

**Issue by biley** [aisuda/amis-editor-demo#77]
如图：
![image](https://user-images.githubusercontent.com/15087577/110303848-d891fc00-8035-11eb-85ad-cc7981f61b8d.png)
添加的自定义组件只能归属于其他吗？有什么方法可以设置归属于表单项、按钮或容器等其余类型吗？

**Comment by lengqingfeng** [comment]
tags 分类的

**Comment by biley** [comment]
是的，更新了文档之后可以分类了。
