### ISSUE TITLE
2.0.9版本编辑器没有图表组件

### ISSUE THREAD

**Issue by lijianmincn** [aisuda/amis-editor-demo#78]
![image](https://user-images.githubusercontent.com/26019815/110471471-203c8480-8117-11eb-9cb3-6aa848518444.png)
新版编辑器没有图表（echarts）组件

**Comment by wibetter** [comment]
请使用新版Editor，目前已升级至4.1.0-beta.24。
![image](https://user-images.githubusercontent.com/11958920/169733483-3d469039-7efb-42ff-928b-71c48a7b14d2.png)
