### ISSUE TITLE
编辑器拖拽组件后不能添加其他组件

### ISSUE THREAD

**Issue by nian-w** [aisuda/amis-editor-demo#81]
![image](https://user-images.githubusercontent.com/80332822/111929714-1ee56180-8af2-11eb-9189-b4ba8b01e8ae.png)
拖拽增删改查组件后，内容区内显示两个表格，点击左侧组件和代码没有反应。保存后，再次进入正常。
自定义组件偶尔也会出现这个问题

**Comment by wibetter** [comment]
旧版amis-editor已不再维护，请使用新版amis-editor（5.2.1-beta.32）。
