### ISSUE TITLE
amis-editor 有计划开源吗？

### ISSUE THREAD

**Issue by Ghostdar** [aisuda/amis-editor-demo#83]
这几天看到这个项目，觉得蛮不错的，可惜amis-eidtor没有开源，一方面不敢使用于业务中，另一方面感觉很多东西都没办法更深层次的定制，想问下有计划把amis-eidtor开源吗？

**Comment by myssea** [comment]
同问

**Comment by muwanou** [comment]
+1

**Comment by remotesc2** [comment]
+1

**Comment by CharellKing** [comment]
+1

**Comment by rumunanfeng** [comment]
+1

**Comment by Jiangshan00001** [comment]
+1

**Comment by beysong** [comment]
+1

**Comment by BingBlog** [comment]
+1

**Comment by webplus** [comment]
+1

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。

**Comment by newwangyiyang** [comment]
+1

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。

**Comment by wibetter** [comment]
短时间内不会开源，有定制化的需求，可以考虑使用我们的爱速搭哈：https://aisuda.bce.baidu.com/。

**Comment by wibetter** [comment]
目前amis-editor已将内置的plugin源码开放出来了，方便各位参照定制自己的自定义组件。组件plugin这部分的源码可以在这里查看：amis-editor-demo/node_modules/amis-editor/src/plugin。

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。

**Comment by wibetter** [comment]
暂无开源计划

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。
