### ISSUE TITLE
本地拉代码跑起来的项目和线上部分样式不一致

### ISSUE THREAD

**Issue by biley** [aisuda/amis-editor-demo#88]
1. 线上编辑时页面的高是撑满了的，而本地跑起来是塌缩的
2. 线上编辑时 右侧栏 =》外观 选择 class 时样式很漂亮，本地跑起来貌似丢失了样式，类似于 'a-ClassNameControl-group' 这样的 class 根本没有作用。

**线上：**
![image](https://user-images.githubusercontent.com/15087577/119764234-9dd88b00-bee3-11eb-89a7-608347695b9d.png)

**本地运行：**
![image](https://user-images.githubusercontent.com/15087577/119764300-b779d280-bee3-11eb-988d-26d8a671ef97.png)

**本地样式 'a-ClassNameControl-group' 无效：**
![image](https://user-images.githubusercontent.com/15087577/119764410-e8f29e00-bee3-11eb-965f-62ea6bbc8b52.png)

**Comment by rongchangchu** [comment]
请问本地下载下代码后，npm i   然后 npm start 空白页是什么问题？

**Comment by wibetter** [comment]
看截图，本地应该是丢了样式。现在可使用新版Editor，目前已升级至4.1.0-beta.24，拉一下最新代码，试下这个版本。
