### ISSUE TITLE
当前服务器  页面新增不i了

### ISSUE THREAD

**Issue by Jiangshan00001** [aisuda/amis-editor-demo#95]
https://aisuda.github.io/amis-editor-demo

GET https://aisuda.github.io/amis-editor-demo/scss/style_c91cc6f.css net::ERR_ABORTED 404

npm_90d8ebe.js:1433 Uncaught (in promise) TypeError: Cannot read property 'props' of null
    at hook2 (npm_90d8ebe.js:1433)
    at Array.r (npm_90d8ebe.js:1034)
    at npm_90d8ebe.js:1463
    at npm_90d8ebe.js:436
    at Object.next (npm_90d8ebe.js:436)
    at npm_90d8ebe.js:480
    at _ (npm_90d8ebe.js:463)
    at n (npm_90d8ebe.js:463)
    at npm_90d8ebe.js:480
    at q (npm_90d8ebe.js:480)
hook2 @ npm_90d8ebe.js:1433
r @ npm_90d8ebe.js:1034
(anonymous) @ npm_90d8ebe.js:1463
(anonymous) @ npm_90d8ebe.js:436
(anonymous) @ npm_90d8ebe.js:436
(anonymous) @ npm_90d8ebe.js:480
_ @ npm_90d8ebe.js:463
n @ npm_90d8ebe.js:463
(anonymous) @ npm_90d8ebe.js:480
q @ npm_90d8ebe.js:480
u @ npm_90d8ebe.js:480
c @ npm_90d8ebe.js:480
Promise.then (async)
l @ npm_90d8ebe.js:480
c @ npm_90d8ebe.js:480
Promise.then (async)
l @ npm_90d8ebe.js:480
c @ npm_90d8ebe.js:480
Promise.then (async)
l @ npm_90d8ebe.js:480
c @ npm_90d8ebe.js:480
o @ npm_90d8ebe.js:480
_ @ npm_90d8ebe.js:463
n @ npm_90d8ebe.js:463
(anonymous) @ npm_90d8ebe.js:480
q @ npm_90d8ebe.js:480
(anonymous) @ npm_90d8ebe.js:480
n @ npm_90d8ebe.js:480
(anonymous) @ npm_90d8ebe.js:1463
(anonymous) @ npm_90d8ebe.js:436
(anonymous) @ npm_90d8ebe.js:436
(anonymous) @ npm_90d8ebe.js:480
_ @ npm_90d8ebe.js:463
n @ npm_90d8ebe.js:463
(anonymous) @ npm_90d8ebe.js:480
q @ npm_90d8ebe.js:480
u @ npm_90d8ebe.js:480
c @ npm_90d8ebe.js:480
o @ npm_90d8ebe.js:480
_ @ npm_90d8ebe.js:463
n @ npm_90d8ebe.js:463
(anonymous) @ npm_90d8ebe.js:480
q @ npm_90d8ebe.js:480
(anonymous) @ npm_90d8ebe.js:480
n @ npm_90d8ebe.js:480
_ @ npm_90d8ebe.js:463
n @ npm_90d8ebe.js:463
(anonymous) @ npm_90d8ebe.js:480
q @ npm_90d8ebe.js:480
r @ npm_90d8ebe.js:480
t.submit @ npm_90d8ebe.js:1841
t.handleAction @ npm_90d8ebe.js:1841
t.handleAction @ npm_90d8ebe.js:1841
t.doAction @ npm_90d8ebe.js:1841
(anonymous) @ npm_90d8ebe.js:1833
t.tryChildrenToHandle @ npm_90d8ebe.js:1833
t.handleAction @ npm_90d8ebe.js:1833
e.handleAction @ npm_90d8ebe.js:1567
e.handleAction @ npm_90d8ebe.js:1567
ca @ npm_90d8ebe.js:117
ja @ npm_90d8ebe.js:118
ka @ npm_90d8ebe.js:118
wa @ npm_90d8ebe.js:120
Aa @ npm_90d8ebe.js:121
ya @ npm_90d8ebe.js:121
Da @ npm_90d8ebe.js:124
Ad @ npm_90d8ebe.js:187
Gi @ npm_90d8ebe.js:353
Kb @ npm_90d8ebe.js:142
Dd @ npm_90d8ebe.js:189
(anonymous) @ npm_90d8ebe.js:354
exports.unstable_runWithPriority @ npm_90d8ebe.js:80
Ii @ npm_90d8ebe.js:354
Cd @ npm_90d8ebe.js:188
Show 41 more frames
npm_90d8ebe.js:480 Uncaught (in promise) Error: [mobx-state-tree] Only promises can be yielded to `async`, got: [object Object]
    at Vt (npm_90d8ebe.js:480)
    at l (npm_90d8ebe.js:480)

**Comment by belongwqz** [comment]
同样问题，求解

**Comment by belongwqz** [comment]
同样问题，求解

**Comment by swtseaman** [comment]
+1

**Comment by 276340452** [comment]
"amis": "1.1.6-beta.24",
"amis-editor": "2.0.13",
降版本后，暂时能用用

**Comment by wibetter** [comment]
目前可以新增页面：
![image](https://user-images.githubusercontent.com/11958920/169732326-d29bf75b-d0c4-4693-8d65-4633d0a13f35.png)
