### ISSUE TITLE
升级后，页面的第一个组件总是提示类型错误，无法渲染

### ISSUE THREAD

**Issue by biley** [aisuda/amis-editor-demo#96]
本地开发： amis 版本 1.2.0,  amis-editor 版本 3.0.4，以及从 github clone 的 amis-editor-demo ：amis 版本 ^1.2.1-beta.9, amis-editor 版本 3.0.4 都存在这个问题：在一个空页面添加第一个组件的时候，会显示类型错误，无法渲染。
如图：
![image](https://user-images.githubusercontent.com/15087577/124894608-64c92580-e00e-11eb-94b6-885055ca3766.png)

此外，还遇到之前写好的 crud 在升级后发请求后卡死的问题，感觉这个升级之后的内容不太稳定啊

**Comment by 2betop** [comment]
1.2.0 的版本有问题，晚点我更新个最新的 beta 版本

**Comment by 2betop** [comment]
用 1.2.1 的 amis 和 3.0.5 的 editor
