### ISSUE TITLE
clone项目到本地，执行npm i之后，无法安装组件。

### ISSUE THREAD

**Issue by getChange** [aisuda/amis-editor-demo#97]
![1626146411551](https://user-images.githubusercontent.com/23140007/125385114-7e7eba00-e3cc-11eb-98f8-7b858a9f84bd.jpg)
git clone项目到本地之后，npm i安装文件，汇报如图错误。使用cnpm i之后依赖可以安装，但是项目无法运行。

**Comment by 2betop** [comment]
把 package-lock.json 删了吧

**Comment by rongchangchu** [comment]
请问可以了，我也是下载zip包后本地起不来

**Comment by wibetter** [comment]
还需要确认一下是不是在外网环境把npm仓库地址配置成了: http://registry.npm.baidu-int.com/。
