### ISSUE TITLE
升级后，卡片组件中有 unknown

### ISSUE THREAD

**Issue by biley** [aisuda/amis-editor-demo#98]
amis 升级到 1.2.1， amis-editor 升级到 3.0.5 或 3.0.6；包括现在线上的 amis 可视化编辑器示例( amis: ^1.2.1, amis-editor: ^3.0.5,)，都存在这样的问题：加入的 card 组件，在左侧的树形中会出现一个 unknown，如图：
![image](https://user-images.githubusercontent.com/15087577/125596880-ce4e5171-42ee-40f8-9211-d2ad480fedb4.png)

**Comment by wibetter** [comment]
请使用新版Editor，目前已升级至4.1.0-beta.24。
