### ISSUE TITLE
amis-editor 的时间展示框 type 错误

### ISSUE THREAD

**Issue by biley** [aisuda/amis-editor-demo#99]
当前线上的可视化编辑器示例中(https://aisuda.github.io/amis-editor-demo/#/hello-world ；版本：amis: ^1.2.1, amis-editor: ^3.0.5)就可以复现的问题：
当选择展示中的日期展示、日期时间展示、时间展示 之后:
![image](https://user-images.githubusercontent.com/15087577/125738848-fc7b9247-79f1-4d3a-88c6-a1a68a179ef5.png)
加入的这三个组件的 type 都是可以选择日期 的 " input-date "（这里的 type 应该是 "date" 才对）:
![image](https://user-images.githubusercontent.com/15087577/125739268-0f2b2651-5c17-4607-8afe-142ea5a3d74a.png)

**Comment by 2betop** [comment]
收到

**Comment by wibetter** [comment]
目前已修正，请使用新版Editor，目前已升级至4.1.0-beta.24。
